package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpsProdutos generated by hbm2java
 */
@Entity
@Table(name="rps_produtos"
    ,catalog="db_rhayan_schonholzer"
)
public class RpsProdutos  implements java.io.Serializable {


     private Integer rpsIdJogo;
     private String rpsNome;
     private Integer rpsGenero;
     private Integer rpsPlataforma;
     private Date rpsAnoLancamento;
     private Integer rpsQuantEstoque;
     private BigDecimal rpsValor;
     private Set rpsVendasProdutoses = new HashSet(0);

    public RpsProdutos() {
    }

	
    public RpsProdutos(String rpsNome, Date rpsAnoLancamento) {
        this.rpsNome = rpsNome;
        this.rpsAnoLancamento = rpsAnoLancamento;
    }
    public RpsProdutos(String rpsNome, Integer rpsGenero, Integer rpsPlataforma, Date rpsAnoLancamento, Integer rpsQuantEstoque, BigDecimal rpsValor, Set rpsVendasProdutoses) {
       this.rpsNome = rpsNome;
       this.rpsGenero = rpsGenero;
       this.rpsPlataforma = rpsPlataforma;
       this.rpsAnoLancamento = rpsAnoLancamento;
       this.rpsQuantEstoque = rpsQuantEstoque;
       this.rpsValor = rpsValor;
       this.rpsVendasProdutoses = rpsVendasProdutoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rps_id_jogo", unique=true, nullable=false)
    public Integer getRpsIdJogo() {
        return this.rpsIdJogo;
    }
    
    public void setRpsIdJogo(Integer rpsIdJogo) {
        this.rpsIdJogo = rpsIdJogo;
    }

    
    @Column(name="rps_nome", nullable=false, length=100)
    public String getRpsNome() {
        return this.rpsNome;
    }
    
    public void setRpsNome(String rpsNome) {
        this.rpsNome = rpsNome;
    }

    
    @Column(name="rps_genero")
    public Integer getRpsGenero() {
        return this.rpsGenero;
    }
    
    public void setRpsGenero(Integer rpsGenero) {
        this.rpsGenero = rpsGenero;
    }

    
    @Column(name="rps_plataforma")
    public Integer getRpsPlataforma() {
        return this.rpsPlataforma;
    }
    
    public void setRpsPlataforma(Integer rpsPlataforma) {
        this.rpsPlataforma = rpsPlataforma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rps_ano_lancamento", nullable=false, length=10)
    public Date getRpsAnoLancamento() {
        return this.rpsAnoLancamento;
    }
    
    public void setRpsAnoLancamento(Date rpsAnoLancamento) {
        this.rpsAnoLancamento = rpsAnoLancamento;
    }

    
    @Column(name="rps_quant_estoque")
    public Integer getRpsQuantEstoque() {
        return this.rpsQuantEstoque;
    }
    
    public void setRpsQuantEstoque(Integer rpsQuantEstoque) {
        this.rpsQuantEstoque = rpsQuantEstoque;
    }

    
    @Column(name="rps_valor", precision=10)
    public BigDecimal getRpsValor() {
        return this.rpsValor;
    }
    
    public void setRpsValor(BigDecimal rpsValor) {
        this.rpsValor = rpsValor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rpsProdutos")
    public Set getRpsVendasProdutoses() {
        return this.rpsVendasProdutoses;
    }
    
    public void setRpsVendasProdutoses(Set rpsVendasProdutoses) {
        this.rpsVendasProdutoses = rpsVendasProdutoses;
    }




}


