package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RpsUsuarios generated by hbm2java
 */
@Entity
@Table(name = "rps_usuarios",
         catalog = "db_rhayan_schonholzer",
         uniqueConstraints = @UniqueConstraint(columnNames = "rps_cpf")
)
public class RpsUsuarios implements java.io.Serializable {

    private int rpsIdusuarios;
    private String rpsNome;
    private String rpsApelido;
    private String rpsCpf;
    private Date rpsDataNascimento;
    private String rpsSenha;
    private int rpsNivel;
    private String rpsAtivo;

    public RpsUsuarios() {
    }

    public RpsUsuarios(String rpsNome, String rpsCpf, Date rpsDataNascimento, String rpsSenha) {
        this.rpsNome = rpsNome;
        this.rpsCpf = rpsCpf;
        this.rpsDataNascimento = rpsDataNascimento;
        this.rpsSenha = rpsSenha;
    }

    public RpsUsuarios(String rpsNome, String rpsApelido, String rpsCpf, Date rpsDataNascimento, String rpsSenha, int rpsNivel, String rpsAtivo) {
        this.rpsNome = rpsNome;
        this.rpsApelido = rpsApelido;
        this.rpsCpf = rpsCpf;
        this.rpsDataNascimento = rpsDataNascimento;
        this.rpsSenha = rpsSenha;
        this.rpsNivel = rpsNivel;
        this.rpsAtivo = rpsAtivo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "rps_idusuarios", unique = true, nullable = false)
    public int getRpsIdusuarios() {
        return this.rpsIdusuarios;
    }

    public void setRpsIdusuarios(int rpsIdusuarios) {
        this.rpsIdusuarios = rpsIdusuarios;
    }

    @Column(name = "rps_nome", nullable = false, length = 100)
    public String getRpsNome() {
        return this.rpsNome;
    }

    public void setRpsNome(String rpsNome) {
        this.rpsNome = rpsNome;
    }

    @Column(name = "rps_apelido", length = 50)
    public String getRpsApelido() {
        return this.rpsApelido;
    }

    public void setRpsApelido(String rpsApelido) {
        this.rpsApelido = rpsApelido;
    }

    @Column(name = "rps_cpf", unique = true, nullable = false, length = 14)
    public String getRpsCpf() {
        return this.rpsCpf;
    }

    public void setRpsCpf(String rpsCpf) {
        this.rpsCpf = rpsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rps_data_nascimento", nullable = false, length = 10)
    public Date getRpsDataNascimento() {
        return this.rpsDataNascimento;
    }

    public void setRpsDataNascimento(Date rpsDataNascimento) {
        this.rpsDataNascimento = rpsDataNascimento;
    }

    @Column(name = "rps_senha", nullable = false)
    public String getRpsSenha() {
        return this.rpsSenha;
    }

    public void setRpsSenha(String rpsSenha) {
        this.rpsSenha = rpsSenha;
    }

    @Column(name = "rps_nivel")
    public int getRpsNivel() {
        return this.rpsNivel;
    }

    public void setRpsNivel(int rpsNivel) {
        this.rpsNivel = rpsNivel;
    }

    @Column(name = "rps_ativo", length = 1)
    public String getRpsAtivo() {
        return this.rpsAtivo;
    }

    public void setRpsAtivo(String rpsAtivo) {
        this.rpsAtivo = rpsAtivo;
    }
}
