package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpsVendas generated by hbm2java
 */
@Entity
@Table(name = "rps_vendas",
        catalog = "db_rhayan_schonholzer"
)
public class RpsVendas implements java.io.Serializable {

    private int rpsIdVendas;
    private RpsClientes rpsClientes;
    private RpsUsuarios rpsUsuarios;
    private Date rpsDataVenda;
    private double rpsTotal;
    private int rpsFormaPagamento;
    private double rpsDesconto;

    public RpsVendas() {
    }

    public RpsVendas(Date rpsDataVenda) {
        this.rpsDataVenda = rpsDataVenda;
    }

    public RpsVendas(RpsClientes rpsClientes, RpsUsuarios rpsUsuarios, Date rpsDataVenda, double rpsTotal, int rpsFormaPagamento, double rpsDesconto) {
        this.rpsClientes = rpsClientes;
        this.rpsUsuarios = rpsUsuarios;
        this.rpsDataVenda = rpsDataVenda;
        this.rpsTotal = rpsTotal;
        this.rpsFormaPagamento = rpsFormaPagamento;
        this.rpsDesconto = rpsDesconto;
    }

    @Id

    @Column(name = "rps_idVendas", unique = true, nullable = false)
    public int getRpsIdVendas() {
        return this.rpsIdVendas;
    }

    public void setRpsIdVendas(int rpsIdVendas) {
        this.rpsIdVendas = rpsIdVendas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rps_cliente")
    public RpsClientes getRpsClientes() {
        return this.rpsClientes;
    }

    public void setRpsClientes(RpsClientes rpsClientes) {
        this.rpsClientes = rpsClientes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rps_usuario")
    public RpsUsuarios getRpsUsuarios() {
        return this.rpsUsuarios;
    }

    public void setRpsUsuarios(RpsUsuarios rpsUsuarios) {
        this.rpsUsuarios = rpsUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rps_dataVenda", nullable = false, length = 10)
    public Date getRpsDataVenda() {
        return this.rpsDataVenda;
    }

    public void setRpsDataVenda(Date rpsDataVenda) {
        this.rpsDataVenda = rpsDataVenda;
    }

    @Column(name = "rps_total", precision = 10)
    public double getRpsTotal() {
        return this.rpsTotal;
    }

    public void setRpsTotal(double rpsTotal) {
        this.rpsTotal = rpsTotal;
    }

    @Column(name = "rps_forma_pagamento", length = 50)
    public int getRpsFormaPagamento() {
        return this.rpsFormaPagamento;
    }

    public void setRpsFormaPagamento(int rpsFormaPagamento) {
        this.rpsFormaPagamento = rpsFormaPagamento;
    }

    @Column(name = "rps_desconto", precision = 10)
    public double getRpsDesconto() {
        return this.rpsDesconto;
    }

    public void setRpsDesconto(double rpsDesconto) {
        this.rpsDesconto = rpsDesconto;
    }

}
