package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RpsVendasProdutos generated by hbm2java
 */
@Entity
@Table(name = "rps_vendas_produtos",
         catalog = "db_rhayan_schonholzer"
)
public class RpsVendasProdutos implements java.io.Serializable {

    private int rpsId;
    private RpsProdutos rpsProdutos;
    private RpsVendas rpsVendas;
    private int rpsQuantidade;
    private double rpsValorUnitario;

    public RpsVendasProdutos() {
    }

    public RpsVendasProdutos(RpsProdutos rpsProdutos, RpsVendas rpsVendas, int rpsQuantidade, double rpsValorUnitario) {
        this.rpsProdutos = rpsProdutos;
        this.rpsVendas = rpsVendas;
        this.rpsQuantidade = rpsQuantidade;
        this.rpsValorUnitario = rpsValorUnitario;
    }

    @Id

    @Column(name = "rps_id", unique = true, nullable = false)
    public int getRpsId() {
        return this.rpsId;
    }

    public void setRpsId(int rpsId) {
        this.rpsId = rpsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rps_produto_id", nullable = false)
    public RpsProdutos getRpsProdutos() {
        return this.rpsProdutos;
    }

    public void setRpsProdutos(RpsProdutos rpsProdutos) {
        this.rpsProdutos = rpsProdutos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rps_venda_id", nullable = false)
    public RpsVendas getRpsVendas() {
        return this.rpsVendas;
    }

    public void setRpsVendas(RpsVendas rpsVendas) {
        this.rpsVendas = rpsVendas;
    }

    @Column(name = "rps_quantidade", nullable = false)
    public int getRpsQuantidade() {
        return this.rpsQuantidade;
    }

    public void setRpsQuantidade(int rpsQuantidade) {
        this.rpsQuantidade = rpsQuantidade;
    }

    @Column(name = "rps_valor_unitario", nullable = false, precision = 10)
    public double getRpsValorUnitario() {
        return this.rpsValorUnitario;
    }

    public void setRpsValorUnitario(double rpsValorUnitario) {
        this.rpsValorUnitario = rpsValorUnitario;
    }

}
