package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RpsVendas generated by hbm2java
 */
@Entity
@Table(name="rps_vendas"
    ,catalog="db_rhayan_schonholzer"
)
public class RpsVendas  implements java.io.Serializable {


     private Integer rpsIdVendas;
     private RpsClientes rpsClientes;
     private RpsUsuarios rpsUsuarios;
     private Date rpsDataVenda;
     private BigDecimal rpsTotal;
     private String rpsFormaPagamento;
     private BigDecimal rpsDesconto;
     private Set rpsVendasProdutoses = new HashSet(0);

    public RpsVendas() {
    }

	
    public RpsVendas(Date rpsDataVenda) {
        this.rpsDataVenda = rpsDataVenda;
    }
    public RpsVendas(RpsClientes rpsClientes, RpsUsuarios rpsUsuarios, Date rpsDataVenda, BigDecimal rpsTotal, String rpsFormaPagamento, BigDecimal rpsDesconto, Set rpsVendasProdutoses) {
       this.rpsClientes = rpsClientes;
       this.rpsUsuarios = rpsUsuarios;
       this.rpsDataVenda = rpsDataVenda;
       this.rpsTotal = rpsTotal;
       this.rpsFormaPagamento = rpsFormaPagamento;
       this.rpsDesconto = rpsDesconto;
       this.rpsVendasProdutoses = rpsVendasProdutoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rps_idVendas", unique=true, nullable=false)
    public Integer getRpsIdVendas() {
        return this.rpsIdVendas;
    }
    
    public void setRpsIdVendas(Integer rpsIdVendas) {
        this.rpsIdVendas = rpsIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rps_cliente")
    public RpsClientes getRpsClientes() {
        return this.rpsClientes;
    }
    
    public void setRpsClientes(RpsClientes rpsClientes) {
        this.rpsClientes = rpsClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rps_usuario")
    public RpsUsuarios getRpsUsuarios() {
        return this.rpsUsuarios;
    }
    
    public void setRpsUsuarios(RpsUsuarios rpsUsuarios) {
        this.rpsUsuarios = rpsUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rps_dataVenda", nullable=false, length=10)
    public Date getRpsDataVenda() {
        return this.rpsDataVenda;
    }
    
    public void setRpsDataVenda(Date rpsDataVenda) {
        this.rpsDataVenda = rpsDataVenda;
    }

    
    @Column(name="rps_total", precision=10)
    public BigDecimal getRpsTotal() {
        return this.rpsTotal;
    }
    
    public void setRpsTotal(BigDecimal rpsTotal) {
        this.rpsTotal = rpsTotal;
    }

    
    @Column(name="rps_forma_pagamento", length=50)
    public String getRpsFormaPagamento() {
        return this.rpsFormaPagamento;
    }
    
    public void setRpsFormaPagamento(String rpsFormaPagamento) {
        this.rpsFormaPagamento = rpsFormaPagamento;
    }

    
    @Column(name="rps_desconto", precision=10)
    public BigDecimal getRpsDesconto() {
        return this.rpsDesconto;
    }
    
    public void setRpsDesconto(BigDecimal rpsDesconto) {
        this.rpsDesconto = rpsDesconto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rpsVendas")
    public Set getRpsVendasProdutoses() {
        return this.rpsVendasProdutoses;
    }
    
    public void setRpsVendasProdutoses(Set rpsVendasProdutoses) {
        this.rpsVendasProdutoses = rpsVendasProdutoses;
    }




}


