package bean;
// Generated 13/10/2025 01:55:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RpsVendedor generated by hbm2java
 */
@Entity
@Table(name = "rps_vendedor",
         catalog = "db_rhayan_schonholzer",
         uniqueConstraints = {
            @UniqueConstraint(columnNames = "rps_cpf")
            , @UniqueConstraint(columnNames = "rps_email")}
)
public class RpsVendedor implements java.io.Serializable {

    private int rpsIdvendedor;
    private String rpsNome;
    private String rpsCpf;
    private String rpsTelefone;
    private Date rpsDataContratacao;
    private String rpsEmail;
    private double rpsSalario;

    public RpsVendedor() {
    }

    public RpsVendedor(String rpsNome, String rpsCpf, Date rpsDataContratacao, String rpsEmail) {
        this.rpsNome = rpsNome;
        this.rpsCpf = rpsCpf;
        this.rpsDataContratacao = rpsDataContratacao;
        this.rpsEmail = rpsEmail;
    }

    public RpsVendedor(String rpsNome, String rpsCpf, String rpsTelefone, Date rpsDataContratacao, String rpsEmail, double rpsSalario) {
        this.rpsNome = rpsNome;
        this.rpsCpf = rpsCpf;
        this.rpsTelefone = rpsTelefone;
        this.rpsDataContratacao = rpsDataContratacao;
        this.rpsEmail = rpsEmail;
        this.rpsSalario = rpsSalario;
    }

    @Id

    @Column(name = "rps_idvendedor", unique = true, nullable = false)
    public int getRpsIdvendedor() {
        return this.rpsIdvendedor;
    }

    public void setRpsIdvendedor(int rpsIdvendedor) {
        this.rpsIdvendedor = rpsIdvendedor;
    }

    @Column(name = "rps_nome", nullable = false, length = 100)
    public String getRpsNome() {
        return this.rpsNome;
    }

    public void setRpsNome(String rpsNome) {
        this.rpsNome = rpsNome;
    }

    @Column(name = "rps_cpf", unique = true, nullable = false, length = 14)
    public String getRpsCpf() {
        return this.rpsCpf;
    }

    public void setRpsCpf(String rpsCpf) {
        this.rpsCpf = rpsCpf;
    }

    @Column(name = "rps_telefone", length = 20)
    public String getRpsTelefone() {
        return this.rpsTelefone;
    }

    public void setRpsTelefone(String rpsTelefone) {
        this.rpsTelefone = rpsTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rps_data_contratacao", nullable = false, length = 10)
    public Date getRpsDataContratacao() {
        return this.rpsDataContratacao;
    }

    public void setRpsDataContratacao(Date rpsDataContratacao) {
        this.rpsDataContratacao = rpsDataContratacao;
    }

    @Column(name = "rps_email", unique = true, nullable = false, length = 100)
    public String getRpsEmail() {
        return this.rpsEmail;
    }

    public void setRpsEmail(String rpsEmail) {
        this.rpsEmail = rpsEmail;
    }

    @Column(name = "rps_salario", precision = 10)
    public double getRpsSalario() {
        return this.rpsSalario;
    }

    public void setRpsSalario(double rpsSalario) {
        this.rpsSalario = rpsSalario;
    }

}
